apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  securityContext:
    runAsUser: 2000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
  containers:
  - name: app
    image: debug-container:latest
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
        add: ["SYS_PTRACE"]
